[package]
name = "macros"
edition = "2021"
version.workspace = true

[dependencies]
syn = { version = "2.0.87", features = ["full"] }
proc-macro2 = "1.0.86"
quote = "1.0.37"
serde_json = "1.0.128"
serde = { version = "1.0.210", features = ["derive"] }
secrets = "1.2.0"

[dev-dependencies]
kvp = {path = "../kvp"}
core = {path = "../core"}

[lib]
proc-macro = true
