[package]
name = "ncp-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

#bcrypt = { version = "0.15.0", features = ["default", "js"] }
hex-literal = "0.4.1"
#hkdf = "0.12"
#sha2 = "0.10.8"
rand = "0.8.5"
dioxus = { version = "*", features = ["fullstack"] }
serde = "1.0.196"
tera = "1.19.1"
strum = "0.26.1"
strum_macros = "0.26.1"
#crypto = { version = "0.5.1", features = ["digest", "password-hash", "cipher", "universal-hash"] }
ring = { version = "0.17.7", features = ["default", "wasm32_unknown_unknown_js", "std"] }
log = "0.4.20"
base64 = "0.22.1"
hex = "0.4.3"
base32 = "0.5.1"
reqwest = "0.12.7"
serde_json = "1.0.113"
serde-inline-default = "0.2.0"
fermi = "0.4.3"
async-std = { version = "1.12.0", features = [] }
instant = "0.1.12"
wasm-bindgen = { version = "0.2.92"}
regex = "1.10.3"
tokio = { version = "1.36.0", features = ["rt", "rt-multi-thread", "macros"], optional = true }
bollard = { version = "0.17.1", optional = true}
dioxus-logger = { version = "0.5" }
sd-notify = { version = "0.4.1" , optional = true}
hyperlocal = { version = "0.9.1", features = ["client"], optional = true }
hyper-util = { version = "0.1.3", features = ["client", "client-legacy", "full", "http1"], optional = true }
hyper = { version = "1.2.0", features = ["client", "full"], optional = true }
http-body-util = { version = "0.1.0", optional = true }
futures-util = "0.3.30"

[dependencies.web-sys]
version = "0.3.70"
features = ["Window", "Location"]

[lib]
name = "ncp_core"
path = "src/lib.rs"

[[bin]]
name = "ncp-config"
path = "src/bin/ncp-config.rs"

[[bin]]
name = "ncp-activation"
path = "src/bin/ncp-activation.rs"

[features]
default = []
ssr = ["dioxus/axum", "tokio", "bollard", "sd-notify", "hyperlocal", "hyper-util", "hyper", "http-body-util"]
web = ["dioxus/web"]

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "target-feature=+crt-static"]
