[package]
name = "ncp-activation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

#bcrypt = { version = "0.15.0", features = ["default", "js"] }
hex-literal = "0.4.1"
#hkdf = "0.12"
#sha2 = "0.10.8"
rand = "0.8.5"
dioxus = "0.4.3"
dioxus-fullstack = "0.4.3"
serde = "1.0.196"
tera = "1.19.1"
strum = "0.26.1"
strum_macros = "0.26.1"
#crypto = { version = "0.5.1", features = ["digest", "password-hash", "cipher", "universal-hash"] }
ring = { version = "0.17.7", features = ["default", "wasm32_unknown_unknown_js"] }
log = "0.4.20"
base64 = "0.21.7"
tokio = { version = "1.36.0", features = ["rt", "rt-multi-thread", "macros"], optional = true }
hex = "0.4.3"
base32 = "0.4.0"
reqwest = "0.11.24"

[features]
default = []
ssr = ["dioxus-fullstack/axum", "tokio"]
web = ["dioxus-fullstack/web"]

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "target-feature=+crt-static"]
