[package]
name = "nextcloud-atomic"
version = "0.1.0"
edition = "2021"

[workspace]
members = [ "packages/activate","packages/caddy", "packages/config/disks", "packages/core", "packages/errors", "packages/kvp", "packages/macros", "packages/model", "packages/ui", "packages/unlock"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
serde = { version = "1.0.196", features = ["default", "derive"] }
thiserror = "1.0.63"
reqwest = "0.12.7"
log = "0.4.20"
regex = "1.10.3"
hyperlocal = { version = "0.9.1", features = ["client"]}
hyper-util = { version = "0.1.3", features = ["client", "client-legacy", "full", "http1"]}
hyper = { version = "1.2.0", features = ["client", "full"]}
http-body-util = { version = "0.1.0" }
anyhow = "1.0.87"
serde_json = "1.0.113"
caddy = {path = 'packages/caddy'}
core = {path = 'packages/core' }
serde-inline-default = "0.2.2"
axum = { version = "0.7", default-features = false, features = ["json", "http1", "tokio"] }
tokio = { features = ["rt", "rt-multi-thread", "macros", "fs"], version = "1", default-features = false }
sysinfo = "0.32.0"
errors = { version = "0.1.0", path = "packages/errors" }
model = { version = "0.1.0", path = "packages/model" }
ui = { version = "0.1.0", path = "packages/ui" }
tera = "1.19.1"
strum = "0.26.1"
strum_macros = "0.26.1"
secrets = "1.2.0"
kvp = {path = "packages/kvp"}

[workspace.package]
version = "0.1.0"

[dependencies]

rand = "0.8.5"
dioxus = { version = "*", features = ["fullstack"] }
ring = { version = "0.17.7", features = ["default", "wasm32_unknown_unknown_js", "std"] }
base64 = "0.22.1"
hex = "0.4.3"
fermi    = "0.4.3"
async-std = { version = "1.12.0", features = [] }
instant = "0.1.12"
wasm-bindgen = { version = "0.2.92"}
bollard = { version = "0.17.1", optional = true}
dioxus-logger = { version = "0.5" }
sd-notify = { version = "0.4.1" , optional = true}
http-body-util = {workspace = true, optional = true}
futures-util = "0.3.30"
tera = {workspace = true, optional = true}
hyper = {workspace = true, optional = true}
hyperlocal = {workspace = true, optional = true}
hyper-util = {workspace = true, optional = true}
serde = {workspace = true}
log = {workspace = true}
regex = {workspace = true}
anyhow = {workspace = true}
axum = {workspace = true, optional = true}
tokio = {workspace = true, optional = true}

caddy = {workspace = true, optional = true}
core = {workspace = true, optional = true}
sysinfo = {workspace = true, optional = true}
errors = {workspace = true, optional = true}
model = {workspace = true, optional = true}
ui = {workspace = true, optional = true}

[dependencies.web-sys]
version = "0.3.70"
features = ["Window", "Location"]

[lib]
name = "ncatomic_core"
path = "src/lib.rs"

[[bin]]
name = "configure"
path = "src/bin/configure.rs"

[[bin]]
name = "activate"
path = "src/bin/activate.rs"

[features]
default = []
server = ["dioxus/axum", "bollard", "sd-notify", "hyperlocal", "hyper-util", "hyper", "http-body-util", "caddy", "core"]
web = ["dioxus/web"]
api = ["tokio", "axum", "sysinfo", "errors", "model", "ui"]

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "target-feature=+crt-static"]
