[package]
name = "ncp-activation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

bcrypt = { version = "0.15.0", features = ["default", "js"] }
hex-literal = "0.4.1"
hkdf = "0.12"
sha2 = "0.10.8"
rand = "0.8.5"
dioxus = "0.4.3"
dioxus-fullstack = "0.4.3"
serde = "1.0.196"

[features]
default = []
ssr = ["dioxus-fullstack/axum"]
web = ["dioxus-fullstack/web"]
