[package]
name = "nextcloud-atomic"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["packages/caddy", "packages/core"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
serde = "1.0.196"
thiserror = "1.0.63"
reqwest = "0.12.7"
log = "0.4.20"
regex = "1.10.3"
hyperlocal = { version = "0.9.1", features = ["client"]}
hyper-util = { version = "0.1.3", features = ["client", "client-legacy", "full", "http1"]}
hyper = { version = "1.2.0", features = ["client", "full"]}
tokio = { version = "1.36.0", features = ["rt", "rt-multi-thread", "macros"]}
http-body-util = { version = "0.1.0" }
anyhow = "1.0.87"
serde_json = "1.0.113"
caddy = {path = 'packages/caddy'}
core = {path = 'packages/core' }
serde-inline-default = "0.2.0"

[workspace.package]
version = "0.1.0"

[dependencies]

rand = "0.8.5"
dioxus = { version = "*", features = ["fullstack"] }
tera = "1.19.1"
strum = "0.26.1"
strum_macros = "0.26.1"
ring = { version = "0.17.7", features = ["default", "wasm32_unknown_unknown_js", "std"] }
base64 = "0.22.1"
hex = "0.4.3"
fermi = "0.4.3"
async-std = { version = "1.12.0", features = [] }
instant = "0.1.12"
wasm-bindgen = { version = "0.2.92"}
tokio = {workspace = true, optional = true}
bollard = { version = "0.17.1", optional = true}
dioxus-logger = { version = "0.5" }
sd-notify = { version = "0.4.1" , optional = true}
http-body-util = {workspace = true, optional = true}
futures-util = "0.3.30"
hyper = {workspace = true, optional = true}
hyperlocal = {workspace = true, optional = true}
hyper-util = {workspace = true, optional = true}
serde = {workspace = true}
log = {workspace = true}
regex = {workspace = true}
anyhow = {workspace = true}

caddy = {workspace = true, optional = true}
core = {workspace = true, optional = true}

[dependencies.web-sys]
version = "0.3.70"
features = ["Window", "Location"]

[lib]
name = "ncp_core"
path = "src/lib.rs"

[[bin]]
name = "configure"
path = "src/bin/configure.rs"

[[bin]]
name = "activate"
path = "src/bin/activate.rs"

[features]
default = []
ssr = ["dioxus/axum", "tokio", "bollard", "sd-notify", "hyperlocal", "hyper-util", "hyper", "http-body-util", "caddy", "core"]
web = ["dioxus/web"]

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "target-feature=+crt-static"]
