[package]
name = "activate"
edition = "2021"
version.workspace = true

[dependencies]
errors = {workspace = true}
axum = {workspace = true}
core = {workspace = true}
tera = {workspace = true}
tempdir = "0.3.7"
secrets = {workspace = true}
key_value_provider = {workspace = true}
lockable_secret = {workspace = true}
lockable_secret_macros = {workspace = true}