[package]
name = "lockable_secret_macros"
edition = "2021"
version.workspace = true

[dependencies]
syn = { version = "2.0.87", features = ["full"] }
proc-macro2 = "1.0.89"
quote = "1.0.37"

[dev-dependencies]
key_value_provider = {workspace = true}
serde_json = "1.0.132"
serde = { version = "1.0.214", features = ["derive"] }
secrets = "1.2.0"
lockable_secret = {workspace = true}

[lib]
proc-macro = true
