[package]
name = "core"
edition = "2021"
version.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = {  workspace = true }
serde-inline-default = {workspace = true}
ring = { version = "0.17.8" }
aead = "0.6.0-rc.0"
digest = "0.11.0-pre.9"
hkdf = "0.13.0-pre.4"
pbkdf2 = "0.13.0-pre.1"
anyhow = {workspace = true}
tera = {workspace = true}
aes-siv = "0.7.0"
secrets = { workspace = true }
strum = {workspace = true}
strum_macros = {workspace = true}
key_value_provider = { workspace = true }
lockable_secret_macros = { workspace = true }
lockable_secret = {workspace = true}
