[package]
name = "caddy"
version = "0.1.0"
edition = "2021"

[dependencies]
hyper = { workspace = true }
log = {workspace = true}
tokio = { workspace = true }
reqwest = {workspace = true}
hyper-util = {workspace = true}
thiserror = {workspace = true}
http-body-util = {workspace = true}
anyhow = {workspace = true}
