[package]
name = "lockable_secret"
edition = "2021"
version.workspace = true

[dependencies]
ring = "0.17.8"
aead = "0.6.0-rc.0"
digest = "0.11.0-pre.9"
hkdf = "0.13.0-pre.4"
pbkdf2 = "0.13.0-pre.1"
serde = { version = "1.0.214", features = ["derive"] }
anyhow = "1.0.93"
serde_json = "1.0.132"
secrets = {workspace = true}
base32 = "0.5.1"
hex = "0.4.3"
hex-literal = "0.4.1"
